points_tracker/models.py
from points_tracker.database import Model, SurrogatePK, Column, db, ReferenceCol, relationship

# models go here

class Audio(SurrogatePK, Model):
    __tablename__ = 'audio'
    name = Column(db.String(50), unique=False)
    length = Column(db.Integer, unique=False)  #stored in seconds
    filename = Column(db.String(32), unique=True)

    @property
    def tag_display(self):
        return ", ".join([tag.tag.lower() 
            for tag in self.tags if not tag.tag == self.name.upper()])
    
    def to_json(self):
        return dict(id=self.id,
                    name=self.name,
                    length=self.length,
                    tags=self.tag_display)

    def __repr__(self):
        return '<Audio %r>' % (self.name)


class AudioTag(SurrogatePK, Model):
    __tablename__ = 'audio_tags'
    tag = Column(db.String(50), unique=False)
    audio_id = Column(db.Integer, db.ForeignKey('audio.id'), nullable=False)
    audio = relationship('Audio', backref="tags")

    def __repr__(self):
        return '<Tag %r>' % (self.tag)

points_tracker/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template, got_request_exception

from points_tracker.assets import assets
from points_tracker.extensions import (
    bcrypt, db, login_manager, migrate, admin
)
from points_tracker import views, models
from points_tracker.auth import views as auth_views

from points_tracker.settings import ProdConfig

def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)

    if (app.config['ADMIN_ENABLED']):
        register_admin_interface(app)

    return app

def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)

def register_admin_interface(app):
    admin.init_app(app)

def register_blueprints(app):
    app.register_blueprint(views.blueprint)
    app.register_blueprint(auth_views.blueprint)

def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)

points_tracker/auth.py
# -*- coding: utf-8 -*-
"""Admin module. Tees up the Flask-SuperAdmin blueprint.
"""
import logging

from flask import render_template
from flask.ext.login import current_user
from flask.ext.superadmin import AdminIndexView, Admin as SuperAdmin
from flask.ext.superadmin.model import ModelAdmin
from points_tracker import models
from points_tracker.extensions import db


class ProtectedModelView(ModelAdmin):

    session = db.session

    def is_accessible(self):
        return role_required('admin').has_role()


class ProtectedAdminIndexView(AdminIndexView):

    def is_accessible(self):
        return current_user.is_admin


class Admin(object):

    def init_app(self, app):
        index_view = ProtectedAdminIndexView(name='Admin Console')
        admin = SuperAdmin(app, 'points_tracker', index_view=index_view)

        admin.register(models.User, ProtectedModelView)

points_tracker/utils/__init__.py
# -*- coding: utf-8 -*-
""" Helper utilities and decorators. """

import random
from flask import flash


def flash_errors(form, category="warning"):
    """ Flash all errors for a form. """
    for field, errors in form.errors.items():
        for error in errors:
            flash("{0} - {1}"
                    .format(getattr(form, field).label.text, error), category)

def generate_token(length=8, alphabet="abcdefghijklmnopqrstuvwxyz0123456789"):
    """ Generate a random token of given length from the specified set of
        characters.  Not guaranteed to be unique.
    """
    return ''.join(random.choice(alphabet) for _ in range(length))

points_tracker/views.py
# -*- coding: utf-8 -*-
"""Main UI section."""
import wave
import contextlib
from . import utils
import os, json, md5
from soco import SoCo
from mutagen.mp3 import MP3
from mutagen.mp4 import MP4
from pydub import AudioSegment
from mutagen.apev2 import APEv2
from models import Audio, AudioTag
from werkzeug import secure_filename
from points_tracker.auth import role_required
from flask.ext.login import login_required, current_user
from flask import Blueprint, Response, render_template, flash, url_for, redirect, request, current_app, send_file

blueprint = Blueprint('main', __name__, static_folder="../static")

###
### The UI application is driven by AngularJS, so a single server-driven
### template and a few helpers are all that is needed, in addition to the API.
###

@blueprint.route("/", methods=["GET"])
@login_required
def dashboard():
    context = {}
    return render_template("points-tracker.html", **context)

@blueprint.route('/get_audio_file/<audio_id>', methods=['GET'])
def get_audio_file(audio_id):

    audio_id = audio_id.replace('.wav', '')

    return send_file(
     current_app.config['UPLOAD_FOLDER']+'/'+audio_id,
     mimetype="audio/wav",
     attachment_filename=audio_id+".wav")

@blueprint.route('/play/<audio_id>', methods=['POST'])
@login_required
def playfile(audio_id):

    a = Audio.query.filter_by(id=audio_id).one()

    if(current_app.config['PLAY_ON_SONOS']):
        sonos = SoCo(current_app.config['SONOS_IP'])

        #get sonos current state before making changes
        volume = sonos.volume

        track = sonos.get_current_track_info()
        sonos.volume = current_app.config['SONOS_VOLUME']
        sonos.play_uri(current_app.config['APP_URL']+'/get_audio_file/'+a.filename+'.wav')

        return 'done'

    #define stream chunk
    chunk = 1024

    #open a wav format music
    f = wave.open(os.path.join(current_app.config['UPLOAD_FOLDER'], a.filename),"rb")
    #instantiate PyAudio
    p = pyaudio.PyAudio()
    #open stream
    stream = p.open(format = p.get_format_from_width(f.getsampwidth()),
                    channels = f.getnchannels(),
                    rate = f.getframerate(),
                    output = True)
    #read data
    data = f.readframes(chunk)

    #paly stream
    while data != '':
        stream.write(data)
        data = f.readframes(chunk)

    #stop stream
    stream.stop_stream()
    stream.close()

    #close PyAudio
    p.terminate()
    return 'done'


@blueprint.route('/files/', defaults={'search_query': None}, methods=['GET'])
@blueprint.route('/files/<search_query>', methods=['GET'])
@login_required
def files(search_query):

    if search_query == None:
        audio = Audio.query.all()
    else:
        if "," in search_query:
            tags = AudioTag.query.filter(AudioTag.tag.in_([term.strip().upper() for term in search_query.split(',')])).all()
        else:
            tags = AudioTag.query.filter(AudioTag.tag.like("%{}%".format(search_query.upper()))).all()
        audio_ids = [tag.audio_id for tag in tags]

        priority = {}
        for tag in tags:
            priority[tag.audio_id] = priority.setdefault(tag.audio_id, 0) + 1

        prioritized_ids = sorted(priority.items(), key=lambda x: x[1], reverse=True)
        audio = Audio.query.filter(Audio.id.in_([pid[0] for pid in prioritized_ids])).all()

    return Response(response=json.dumps([a.to_json() for a in audio]))

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in current_app.config['ALLOWED_EXTENSIONS']

@blueprint.route("/files/", methods=["POST"])
@login_required
def upload_file():
    if request.method == 'POST':
        if request.files:
            file = request.files['file']

            if allowed_file(file.filename):

                #save file to disk
                filename, extension = os.path.splitext(file.filename)
                filenamehash = md5.new(secure_filename(filename)).hexdigest()
                filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filenamehash)

                with open(filepath, 'w') as disk_file:
                    pass
                file.save(filepath)

                audiofile = AudioSegment.from_file(filepath, extension[1:])                         #load the file
                audiofile = audiofile[:current_app.config['MAX_AUDIO_DURATION_MS']]                 #trim the file
                audiofile = audiofile + -(audiofile.dBFS - current_app.config['AUDIO_DB_LEVEL'])    #level the file
                audiofile.export(filepath, "wav")                                                   #save our changes to disk

                #create the db record of the file
                audio = Audio.create(
                        name= request.form['audioName'],
                        filename= filenamehash,
                        length= audiofile.duration_seconds)

                # add the tags
                tags = [AudioTag.create(tag=tag, audio_id=audio.id) for tag in (request.form['audioName']+','+request.form['audioTags']).upper().split(',')]

    return Response(response=json.dumps({}))

points_tracker/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page.
    </div>
</div>
{% endblock %}

points_tracker/templates/dashboard.html
{% extends "layout.html" %}

  {% block content %}
  <div ui-view><h1>Hello, World!</h1></div>
  {% endblock %}

points_tracker/templates/layout.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}points_tracker{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">
  <link rel="icon" type="image/gif" href="{{ url_for('static', filename='images/favicon.ico') }}">
  <link href='//fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">

  {% assets "app_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
  {% assets "vendor_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
  {% block css %}{% endblock %}

</head>
<body ng-app="points_tracker" class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form, layout=self %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>

{% block container_start %}
<div class="container">
{% endblock %}

  <div role="main">
    <toaster-container toaster-options="{'time-out': 3000, 'close-button':true}"></toaster-container>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div ng-controller="FlaskToasterCtrl as ctrl" >
          {% for category, message in messages %}
            <div style="display:none;" class="flask-message flask-message-{{loop.index0}}">{{message}}</div>
            <div style="display:none;" class="flask-category">{{category}}</div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>

{% block container_end %}
</div>
{% endblock %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "vendor_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "angular_templates_js" %}
  {% if config['ASSETS_DEBUG'] %}
  <script type="text/javascript">
    angular.module('flask-assets-templates', []);
  </script>
  {% else %}
  <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endif %}
{% endassets %}
{% assets "app_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %} 
<script type="text/javascript">
  window.HUE = {{hue_settings|safe}};
</script>
<!-- end scripts -->
{% endblock %}
</body>
</html>

points_tracker/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  {{ layout.container_start() }}

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.dashboard') }}#/">Poor Floor Stamp Management System</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
      {% if not (current_user and current_user.is_authenticated()) %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% else %}
      <li>
        <a href="/#/lights" title="audio list"><i class="fa fa-lightbulb-o fa-lg"></i></a>
      </li>
      <li>
        <a href="/#/audio-list" title="audio list"><i class="fa fa-music fa-lg"></i></a>
      </li>
        <li class="dropdown">
          <a href="javascript://" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" title="Settings"><i class="fa fa-cog fa-lg"></i></a>
          <ul class="settings-menu dropdown-menu" role="menu">
            <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
            {% if current_user.has_role('admin') %}
            <li class="divider"></li>
            <li><a href="{{ url_for('auth.user_list') }}">Manage Users</a></li>
            {% endif %}
            {% if current_user.has_role('superadmin') %}
            <li class="divider"></li>
            <li><a href="{{ url_for('admin.index') }}">Admin Console</a></li>
            {% endif %}
          </ul>
        </li>
        <li><a href="{{ url_for('auth.logout') }}" title="Log out {{ current_user.username }}"><i class="fa fa-power-off fa-lg"></i></a></li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->

  {{ layout.container_end() }}
</nav>

points_tracker/templates/points-tracker.html
{% extends "layout.html" %}

  {% block content %}
  <div ui-view></div>
  {% endblock %}